apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - serviceaccounts
  - configmaps
  - services
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentbit.fluent.io
  resources:
  - collectors
  - fluentbits
  - fluentbits/finalizers
  - clusterfluentbitconfigs
  - clusterfluentbitconfigs/finalizers
  - clusterfilters
  - clusterfilters/finalizers
  - clusterinputs
  - clusterinputs/finalizers
  - clusteroutputs
  - clusteroutputs/finalizers
  - clusterparsers
  - clusterparsers/finalizers
  - fluentbitconfigs
  - fluentbitconfigs/finalizers
  - multilineparsers
  - multilineparsers/finalizers
  - clustermultilineparsers
  - clustermultilineparsers/finalizers
  - filters
  - outputs
  - parsers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fluentd.fluent.io
  resources:
  - fluentds
  - fluentds/status
  - clusterfluentdconfigs
  - clusterfluentdconfigs/status
  - fluentdconfigs
  - fluentdconfigs/status
  - clusterfilters
  - filters
  - clusteroutputs
  - outputs
  - inputs
  - clusterinputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - create
  - list
  - get
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - create
  - list
  - get
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - list
  - get
  - watch
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - list
  - get
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-operator
subjects:
- kind: ServiceAccount
  name: fluent-operator
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-env
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
data:
  fluent-bit.env: |
    CONTAINER_ROOT_DIR=/var/log
---
# Source: fluent-operator/templates/fluent-operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-operator
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluent-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluent-operator
    spec:
      volumes:
      - name: env
        configMap:
          name: fluent-bit-env
      imagePullSecrets:
      - name: core # kpt-set: ${CORE_IMG_CREDENTIALS}
      containers:
      - name: fluent-operator
        image: ghcr.io/nokia-eda/ext/fluent/fluent-operator/fluent-operator:3.4.0 # kpt-set: ${FO_IMG}
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        args:
        - --disable-component-controllers=fluentd
        volumeMounts:
        - name: env
          mountPath: /fluent-operator
      serviceAccountName: fluent-operator
