apiVersion: core.eda.nokia.com/v1
kind: HttpProxy
metadata:
  name: gogs-replica
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  authType: atDestination
  rootUrl: http://eda-git-replica:3000/
