apiVersion: core.eda.nokia.com/v1
kind: ClusterRole
metadata:
  name: system-administrator
  namespace: default
spec:
  description: This is the default administrator role for EDA. It cannot be deleted.  A user with this role can do anything.
  resourceRules:
  - apiGroups:
    - '*'
    permissions: readWrite
    resources:
    - '*'
  tableRules:
  - path: '.**'
    permissions: read
  urlRules:
  - path: '/**'
    permissions: readWrite
