apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: srlinux-ghcr-25.3.2
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
spec:
  nodeUser: admin
  operatingSystem: srl
  port: 57400
  version: 25.3.2
  versionPath: .system.information.version
  versionMatch: v25\.3\.2.*
  yang: https://eda-asvr.eda-system.svc/eda-system/schemaprofiles/srlinux-ghcr-25.3.2/srlinux-25.3.2.zip # kpt-set: https://eda-asvr.${EDA_CORE_NAMESPACE}.svc/${EDA_CORE_NAMESPACE}/schemaprofiles/srlinux-ghcr-25.3.2/srlinux-25.3.2.zip
  llmDb: https://eda-asvr.eda-system.svc/eda-system/llm-dbs/llm-db-srlinux-ghcr-25.3.2/llm-embeddings-srl-25-3-2.tar.gz # kpt-set: https://eda-asvr.${EDA_CORE_NAMESPACE}.svc/${EDA_CORE_NAMESPACE}/llm-dbs/llm-db-srlinux-ghcr-25.3.2/llm-embeddings-srl-25-3-2.tar.gz
  dhcp:
    managementPoolv4: 'ipv4-mgmt-pool'
    dhcp4Options:
    - option: 6-DomainNameServer
      value:
      - 128.251.10.125
  license: cx-srl-25-3-2-ghcr-license
  images:
  - image: eda-system/srlimages/srlinux-25.3.2-312 # kpt-set: ${EDA_CORE_NAMESPACE}/srlimages/srlinux-25.3.2-312
    imageMd5: eda-system/srlimages/srlinux-25.3.2-312-md5 # kpt-set: ${EDA_CORE_NAMESPACE}/srlimages/srlinux-25.3.2-312-md5
  containerImage: ghcr.io/nokia/srlinux:25.3.2-312 # kpt-set: ${SRL_25_3_2_GHCR}
  imagePullSecret: core # kpt-set: ${CORE_IMG_CREDENTIALS}
