apiVersion: v1
kind: Namespace
metadata:
  name: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/core-ns: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
    kubernetes.io/metadata.name: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
