apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eda-internal-ca
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  isCA: true
  commonName: eda-internal-ca
  subject:
    organizations:
      - Nokia
    organizationalUnits:
      - NI
  secretName: eda-internal-ca
  secretTemplate:
    labels:
      eda.nokia.com/ca: "internal"
  usages:
    - digital signature
    - cert sign
    - key encipherment
    - server auth
    - client auth
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  duration: 2160h
  renewBefore: 1440h
  issuerRef:
    name: eda-root-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eda-internal-issuer
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  ca:
    secretName: eda-internal-ca
