apiVersion: core.eda.nokia.com/v1
kind: HttpProxy
metadata:
  name: docs
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  rootUrl: https://eda-appstore.{EDA_CORE_NAMESPACE}.svc:8082/
  authType: atDestination
