apiVersion: core.eda.nokia.com/v1
kind: HttpProxy
metadata:
  name: keycloak
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  authType: atDestination
  rootUrl: https://eda-keycloak.eda-system.svc:9443/core/proxy/v1/identity # kpt-set: https://eda-keycloak.${EDA_CORE_NAMESPACE}.svc:9443/core/proxy/v1/identity
