apiVersion: v1
data:
  password: Z2l0aHViX3BhdF8xMUJLWTZHT1kwUE9nUldYcHQzZkR6X3VZVVNvUkJNdFhBWEwzWGdpcUR1Z1BrZTNWUjZIWVlScnVTUW5UcXNyUFhURVBBVjdFS0Y4YnFXZnhm
  username: bm9raWEtZWRhLWJvdA==
kind: Secret
metadata:
  name: gh-catalog
