apiVersion: appstore.eda.nokia.com/v1
kind: Registry
metadata:
  name: eda-apps-registry
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  remoteURL: ghcr.io # kpt-set: ${APP_REGISTRY}
  authSecretRef: appstore-gh-registry
  skipTLSVerify: false # kpt-set: ${APP_REGISTRY_SKIPTLSVERIFY}
  mirror: "" # kpt-set: ${APP_REGISTRY_MIRROR}
