apiVersion: v1
data:
  password: Z2hwX3hYUDh4bGlSYmRYTldwMlhQM2w0NzFoOXFadHFzUjE4UklCVw==
  username: bm9raWEtZWRhLWJvdA==
kind: Secret
metadata:
  name: appstore-gh-registry
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/backup: "true"