apiVersion: v1
kind: ConfigMap
metadata:
  name: cx-srl-24-10-1-ghcr-license
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/backup: "true"
data:
  license.key: ""
