apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf
        Daemon        off

    [INPUT]
        Name              tail
        Tag               kube.*
        #Tag               <container_name>-<namespace_name>
        Parser            cri
        Path              /var/log/containers/eda*.log
        Exclude_Path      *fluent-bit*, *fluentd*
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     250M
        Skip_Long_Lines   On
        Refresh_Interval  5

    [FILTER]
        Name                kubernetes
        Match               kube.*
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Merge_Log           On
        Keep_Log            Off

    [OUTPUT]
        Name          forward
        Match         *
        Host          ${FLUENTD_HOST}
        Port          ${FLUENTD_PORT}
        Retry_Limit   False

    #[FILTER]
    #    Name        modify
    #    Match       *
    #    Add         pod_name $.kubernetes.pod_name
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) [^ ]+ (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eda-fluentbit
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  selector:
    matchLabels:
      name: eda-fluentbit
      app: eda-fluentbit
  template:
    metadata:
      labels:
        name: eda-fluentbit
        app: eda-fluentbit
    spec:
      imagePullSecrets:
      - name: core # kpt-set: ${CORE_IMG_CREDENTIALS}
      containers:
      - name: fluent-bit
        securityContext:
          privileged: true
        image: ghcr.io/nokia-eda/core/fluent-bit:3.0.7-amd64 # kpt-set: ${FB_IMG}
        env:
        - name: FLUENTD_HOST
          value: "fluentd.eda-system.svc" # kpt-set: fluentd.${EDA_CORE_NAMESPACE}.svc
        - name: FLUENTD_PORT
          value: "24224"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlogcontainers
          mountPath: /var/log/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
