apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/app: fluentd
spec:
  ports:
  - port: 24224
    protocol: TCP
  selector:
    eda.nokia.com/app: fluentd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
data:
  edafluent.conf: "<source>\n  @type forward\n  port 24224\n  bind 0.0.0.0\n  @label @INPUT\n</source>\n\n<source>\n  @type forward\n  port 24224\n  bind ::\n  @label @INPUT\n</source>\n\n<label @INPUT>\n  <filter **>\n    @type record_transformer\n    remove_keys time\n  </filter>\n  <match **>\n    @type relabel\n    @label @EDAAPPLABEL\n  </match>\n</label>\n\n<label @EDAAPPLABEL>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key $['kubernetes']['labels']['eda.nokia.com/app']\n      pattern /^(.+)$/\n      tag $1\n      label @EDAGROUPLABEL\n    </rule>\n    <rule>\n      key $['kubernetes']['labels']['eda.nokia.com/app']\n      pattern /^(.+)$/\n      invert true\n      tag ${tag}\n      label @OUTPUT\n    </rule>\n  </match>\n</label>\n\n<label @EDAGROUPLABEL>\n  <match **>\n    @type rewrite_tag_filter\n    remove_tag_prefix kube.var.log.containers\n    <rule>\n      key $['kubernetes']['labels']['eda.nokia.com/app-group']\n      pattern /^(.+)$/\n      tag $1.${tag}\n      label @EDAPODLOGGER\n    </rule>\n    <rule>\n      key $['kubernetes']['labels']['eda.nokia.com/app-group']\n      pattern /^(.+)$/\n      invert true\n      tag nogroup.${tag}\n      label @EDAPODLOGGER\n    </rule>\n  </match>\n</label>\n\n<label @EDAPODLOGGER>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key $['kubernetes']['pod_name']\n      pattern /^(.+)$/\n      tag ${tag}.$1\n      label @EDACONTAINERLOGGER\n    </rule>\n    <rule>\n      key $['kubernetes']['pod_name']\n      pattern /^(.+)$/\n      invert true\n      tag ${tag}\n      label @OUTPUT\n    </rule>\n  </match>\n</label>\n\n<label @EDACONTAINERLOGGER>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key $['kubernetes']['container_name']\n      pattern /^(.+)$/\n      tag ${tag}__$1\n      label @EDAAPPSPECIFICLOGGER\n    </rule>\n    <rule>\n      key $['kubernetes']['container_name']\n      pattern /^(.+)$/\n      invert true\n      tag ${tag}\n      label @OUTPUT\n    </rule>\n  </match>\n</label>\n\n<label @EDAAPPSPECIFICLOGGER>\n  <match control-plane.apiserver.**>\n    @type relabel\n    @label @EDAAPPAPISERVERLOGGER\n  </match>\n  <match git-plane.git.**>\n    @type relabel\n    @label @EDAFILELOGGER\n  </match>\n  <match git-replica-plane.git-replica.**>\n    @type relabel\n    @label @EDAFILELOGGER\n  </match>\n  <match toolbox.eda-toolbox.**>\n    @type relabel\n    @label @EDAFILELOGGER\n  </match>\n  <match **>\n    @type relabel\n    @label @EDAERRORDETECTOR\n  </match>\n</label>\n\n<label @EDAAPPAPISERVERLOGGER>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key logger\n      pattern /access/\n      tag ${tag}\n      label @EDAAPPAPISERVERACCESSHANDLER\n    </rule>\n    <rule>\n      key logger\n      pattern /access/\n      invert true\n      tag ${tag}\n      label @EDAERRORDETECTOR\n    </rule>\n  </match>\n</label>\n\n<label @EDAAPPAPISERVERACCESSHANDLER>\n  <match **>\n    @type copy\n    <store>\n      @type relabel\n      @label @EDAAPPAPISERVERACCESSLOGGER\n    </store>\n    <store>\n      @type relabel\n      @label @EDAERRORDETECTOR\n    </store>\n  </match>\n</label>\n\n<label @EDAAPPAPISERVERACCESSLOGGER>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key dummywillnotbefound\n      pattern /^(.+)$/\n      invert true\n      # tag ${tag_parts[0]}.${tag_parts[1]}.access\n      tag \"access\"\n      label @EDAFILELOGGER\n    </rule>\n  </match>\n</label>\n\n<label @EDAERRORDETECTOR>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key stream\n      pattern /stderr/\n      tag ${tag}\n      label @EDAERRORCOPIER\n    </rule>\n    # We will uncomment this for use in future\n    #<rule>\n    #  key log\n    #  pattern /error/i\n    #  tag ${tag}\n    #  label @EDAERRORCOPIER\n    #</rule>\n    <rule>\n      key stream\n      pattern /stderr/\n      invert true\n      tag ${tag}\n      label @EDAFILELOGGER\n    </rule>\n  </match>\n</label>\n\n<label @EDAERRORCOPIER>\n  <match **>\n    @type copy\n    <store>\n      @type relabel\n      @label @EDAFILELOGGER\n    </store>\n    <store>\n      @type relabel\n      @label @EDAERRORCOMMONLOGGER\n    </store>\n  </match>\n</label>\n\n<label @EDAERRORCOMMONLOGGER>\n  <match **>\n    @type rewrite_tag_filter\n    <rule>\n      key dummywillnotbefound\n      pattern /^(.+)$/\n      invert true\n      tag errors.${tag}\n      label @EDAFILELOGGERNONJSON\n    </rule>\n  </match>\n</label>\n\n<label @EDAFILELOGGERNONJSON>\n  <filter **>\n    @type record_transformer\n    remove_keys stream,$.kubernetes.labels,$.kubernetes.pod_name,$.kubernetes.namespace_name,$.kubernetes.pod_id,$.kubernetes.container_name,$.kubernetes.docker_id,$.kubernetes.container_hash,$.kubernetes.container_image\n  </filter>\n  <match **>\n    @type file\n    path /var/log/eda/${tag[0]}\n    append true\n    <buffer tag>\n      @type memory\n      chunk_limit_size 16m        \n      total_limit_size 1g        \n      flush_mode interval           \n      flush_interval 2s             \n      flush_thread_count 2          \n      overflow_action drop_oldest_chunk  \n      retry_max_times 5             \n      retry_wait 2s \n    </buffer>\n  </match>\n</label>\n\n<label @EDAFILELOGGER>\n  <filter **>\n    @type record_transformer\n    remove_keys stream,$.kubernetes.labels,$.kubernetes.pod_name,$.kubernetes.namespace_name,$.kubernetes.pod_id,$.kubernetes.container_name,$.kubernetes.docker_id,$.kubernetes.container_hash,$.kubernetes.container_image\n  </filter>\n  <match **.access>\n    @type file\n    # the tag[100] is a workaround because the buffer usage mandates it\n    path /var/log/eda/${tag[100]}access\n    append true\n    <format>\n      @type json\n    </format>\n    <buffer tag>\n      @type memory\n      chunk_limit_size 16m        \n      total_limit_size 1g        \n      flush_mode interval           \n      flush_interval 2s             \n      flush_thread_count 2          \n      overflow_action drop_oldest_chunk  \n      retry_max_times 5             \n      retry_wait 2s \n    </buffer>\n  </match>\n  <match **>\n    @type file\n    path /var/log/eda/${tag[0]}/${tag[1]}/${tag[2]}\n    append true\n    <format>\n      @type json\n    </format>\n    <buffer tag>\n      @type memory\n      chunk_limit_size 16m        \n      total_limit_size 1g        \n      flush_mode interval           \n      flush_interval 2s             \n      flush_thread_count 2          \n      overflow_action drop_oldest_chunk  \n      retry_max_times 5             \n      retry_wait 2s \n    </buffer>\n  </match>\n</label>\n\n<label @OUTPUT>\n  <match **>\n    @type file\n    path /var/log/eda/unknown/${tag}\n    append true\n    <buffer tag>\n      @type memory\n      chunk_limit_size 16m        \n      total_limit_size 1g        \n      flush_mode interval           \n      flush_interval 2s             \n      flush_thread_count 2          \n      overflow_action drop_oldest_chunk  \n      retry_max_times 5             \n      retry_wait 2s \n    </buffer>\n  </match>\n</label>\n\n<match **>\n  @type file\n  path /var/log/eda/others/${tag}\n  append true\n  <buffer tag>\n    @type memory\n      chunk_limit_size 16m        \n      total_limit_size 1g        \n      flush_mode interval           \n      flush_interval 2s             \n      flush_thread_count 2          \n      overflow_action drop_oldest_chunk  \n      retry_max_times 5             \n      retry_wait 2s \n  </buffer>\n</match>\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-fluentd
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/app: fluentd
    eda.nokia.com/app-group: log-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      eda.nokia.com/app: fluentd
  template:
    metadata:
      labels:
        eda.nokia.com/app-group: log-plane
        eda.nokia.com/app: fluentd
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: eda.nokia.com/app-group
                      operator: In
                      values:
                        - log-plane
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: eda.nokia.com/app-group
                    operator: In
                    values:
                      - log-plane
      imagePullSecrets:
        - name: core # kpt-set: ${CORE_IMG_CREDENTIALS}
      volumes:
        - name: fluentd-config-volume
          configMap:
            name: fluentd-config
      containers:
        - name: eda-fluentd
          image: ghcr.io/nokia-eda/core/fluentd:v1.17.0-debian-1.0 # kpt-set: ${FD_IMG}
          securityContext:
            privileged: true
          volumeMounts:
            - name: fluentd-config-volume
              mountPath: /fluentd/etc/edafluent.conf
              subPath: edafluent.conf
          env:
            - name: FLUENTD_CONF
              value: "edafluent.conf"
          resources:
            limits:
              memory: 5Gi
            requests:
              cpu: 100m
              memory: 200Mi
