apiVersion: artifacts.eda.nokia.com/v1
kind: Artifact
metadata:
  name: srlinux-ghcr-26.3.1
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  repo: schemaprofiles
  filePath: srlinux-26.3.1.zip
  remoteFileUrl:
    fileUrl: https://github.com/nokia-eda/schema-profiles/releases/download/nokia-srl-26.3.1/srlinux-26.3.1-410.zip # kpt-set: ${YANG_REMOTE_URL}/srlinux-26.3.1-410.zip
