apiVersion: core.eda.nokia.com/v1
kind: EngineConfig
metadata:
  name: engine-config # kpt-set: ${CLUSTER_MEMBER_NAME}
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  git:
    servers: # kpt-set: ${GIT_SERVERS}
      - credential: git-secret
        uri: http://eda-git-replica:3000
        name: replica
      - credential: git-secret
        uri: http://eda-git:3000
        name: primary
  cluster:
    external:
      domainName: "" # kpt-set: ${EXT_DOMAIN_NAME}
      relaxDomainNameEnforcement: false # kpt-set: ${EXT_RELAX_DOMAIN_NAME_ENFORCEMENT}
      httpPort: 0 # kpt-set: ${EXT_HTTP_PORT}
      httpsPort: 0 # kpt-set: ${EXT_HTTPS_PORT}
      ipv4Address: "" # kpt-set: ${EXT_IPV4_ADDR}
      ipv6Address: "" # kpt-set: ${EXT_IPV6_ADDR}
    internal:
      httpPort: 80 # kpt-set: ${INT_HTTP_PORT}
      httpsPort: 443 # kpt-set: ${INT_HTTPS_PORT}
  checkpoint-git-repo:
    remote-path: /eda/customresources.git # kpt-set: ${GIT_REPO_CHECKPOINT}
  scripts-git-repo:
    remote-path: /eda/apps.git # kpt-set: ${GIT_REPO_APPS}
  user-settings-git-repo:
    remote-path: /eda/usersettings.git # kpt-set: ${GIT_REPO_USER_SETTINGS}
  certificate-git-repo:
    remote-path: /eda/credentials.git # kpt-set: ${GIT_REPO_SECURITY}
  identity-git-repo:
    remote-path: /eda/identity.git # kpt-set: ${GIT_REPO_IDENTITY}
  artifactServer:
    image: ghcr.io/nokia-eda/core/artifact-server:25.8.3 # kpt-set: ${ASVR_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${ASVR_LIMIT_CPU}
        memory: "" # kpt-set: ${ASVR_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${ASVR_REQ_CPU}
        memory: "" # kpt-set: ${ASVR_REQ_MEM}
  bootstrapServer:
    image: ghcr.io/nokia-eda/core/bootstrap-server:25.8.3 # kpt-set: ${BSVR_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${BSVR_LIMIT_CPU}
        memory: "" # kpt-set: ${BSVR_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${BSVR_REQ_CPU}
        memory: "" # kpt-set: ${BSVR_REQ_MEM}
  certChecker:
    image: ghcr.io/nokia-eda/core/cert-checker:25.8.3 # kpt-set: ${ECC_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${ECC_LIMIT_CPU}
        memory: "" # kpt-set: ${ECC_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${ECC_REQ_CPU}
        memory: "" # kpt-set: ${ECC_REQ_MEM}
  cx:
    image: ghcr.io/nokia-eda/core/cx:25.8.3 # kpt-set: ${CX_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${CX_LIMIT_CPU}
        memory: "" # kpt-set: ${CX_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${CX_REQ_CPU}
        memory: "" # kpt-set: ${CX_REQ_MEM}
  cxCluster:
    isCxAgent: false #kpt-set: ${CXCLUSTER_ISAGENT}
    address: eda-cx-standalone #kpt-set: ${CXCLUSTER_ADDR}
    port: 52200 #kpt-set: ${CXCLUSTER_PORT}
  metricsServer:
    image: ghcr.io/nokia-eda/core/metrics-server:25.8.3 # kpt-set: ${EMS_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${EMS_LIMIT_CPU}
        memory: "" # kpt-set: ${EMS_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${EMS_REQ_CPU}
        memory: "" # kpt-set: ${EMS_REQ_MEM}
  npp:
    image: ghcr.io/nokia-eda/core/npp:25.8.3 # kpt-set: ${NPP_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${NPP_LIMIT_CPU}
        memory: "" # kpt-set: ${NPP_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${NPP_REQ_CPU}
        memory: "" # kpt-set: ${NPP_REQ_MEM}
  stateEngine:
    image: ghcr.io/nokia-eda/core/state-engine:25.8.3 # kpt-set: ${SE_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    replicas: 1 # kpt-set: ${SE_REPLICAS}
    resources:
      limits:
        cpu: "" # kpt-set: ${SE_LIMIT_CPU}
        memory: "" # kpt-set: ${SE_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${SE_REQ_CPU}
        memory: "" # kpt-set: ${SE_REQ_MEM}
  stateAggregator:
    image: ghcr.io/nokia-eda/core/state-aggregator:25.8.3 # kpt-set: ${SA_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    replicas: 1 # kpt-set: ${SA_REPLICAS}
    resources:
      limits:
        cpu: "" # kpt-set: ${SA_LIMIT_CPU}
        memory: "" # kpt-set: ${SA_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${SA_REQ_CPU}
        memory: "" # kpt-set: ${SA_REQ_MEM}
  stateController:
    image: ghcr.io/nokia-eda/core/state-controller:25.8.3 # kpt-set: ${SC_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${SC_LIMIT_CPU}
        memory: "" # kpt-set: ${SC_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${SC_REQ_CPU}
        memory: "" # kpt-set: ${SC_REQ_MEM}
  flowEngine:
    image: ghcr.io/nokia-eda/core/flow-engine:25.8.3 # kpt-set: ${FE_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${FE_LIMIT_CPU}
        memory: "" # kpt-set: ${FE_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${FE_REQ_CPU}
        memory: "" # kpt-set: ${FE_REQ_MEM}
  api:
    image: ghcr.io/nokia-eda/core/api-server:25.8.3 # kpt-set: ${API_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    replicas: 1 # kpt-set: ${API_REPLICAS}
    enableLoadBalancerNodePorts: false # kpt-set: ${API_SVC_ENABLE_LB_NODE_PORTS}
    resources:
      limits:
        cpu: "" # kpt-set: ${API_LIMIT_CPU}
        memory: "" # kpt-set: ${API_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${API_REQ_CPU}
        memory: "" # kpt-set: ${API_REQ_MEM}
  appStore:
    image: ghcr.io/nokia-eda/core/appstore-server:25.8.3 # kpt-set: ${ASC_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${ASC_LIMIT_CPU}
        memory: "" # kpt-set: ${ASC_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${ASC_REQ_CPU}
        memory: "" # kpt-set: ${ASC_REQ_MEM}
  appStoreFlow:
    image: ghcr.io/nokia-eda/core/appstore-flow:25.8.3 # kpt-set: ${ASF_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
  testMan:
    image: ghcr.io/nokia-eda/core/testman:25.8.3 # kpt-set: ${TM_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${TM_LIMIT_CPU}
        memory: "" # kpt-set: ${TM_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${TM_REQ_CPU}
        memory: "" # kpt-set: ${TM_REQ_MEM}
  identity:
    image: ghcr.io/nokia-eda/core/eda-keycloak:25.8.3 # kpt-set: ${KC_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${KC_LIMIT_CPU}
        memory: "" # kpt-set: ${KC_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${KC_REQ_CPU}
        memory: "" # kpt-set: ${KC_REQ_MEM}
  identitydb:
    image: ghcr.io/nokia-eda/core/eda-postgres:25.8.3 # kpt-set: ${PG_IMG}
    image-credential: core # kpt-set: ${CORE_IMG_CREDENTIALS}
    resources:
      limits:
        cpu: "" # kpt-set: ${PG_LIMIT_CPU}
        memory: "" # kpt-set: ${PG_LIMIT_MEM}
      requests:
        cpu: "" # kpt-set: ${PG_REQ_CPU}
        memory: "" # kpt-set: ${PG_REQ_MEM}
  llm:
    apiKey: "" # kpt-set: ${LLM_API_KEY}
    model: gpt-4o # kpt-set: ${LLM_MODEL}
  simulate: true # kpt-set: ${SIMULATE}
  singleStackServices: false # kpt-set: ${SINGLESTACK_SVCS}
