apiVersion: aaa.eda.nokia.com/v1alpha1
kind: NodeGroup
metadata:
  name: sudo
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  services:
    - GNMI
    - CLI
    - NETCONF
  superuser: true
