apiVersion: core.eda.nokia.com/v1
kind: NodeUser
metadata:
  name: admin
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  username: admin
  password: eda124!
  groupBindings:
  - nodeSelector:
    - ""
    # - "eda.nokia.com/role=spine"
    # - "eda.nokia.com/role=borderleaf"
    # - "eda.nokia.com/role=leaf"
    # - "eda.nokia.com/pod=1"
    groups:
    - "sudo"
