apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-toolbox
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/app-group: control-plane
    eda.nokia.com/app: eda-toolbox
spec:
  selector:
    matchLabels:
      eda.nokia.com/app: eda-toolbox
  replicas: 1
  template:
    metadata:
      labels:
        eda.nokia.com/app-group: control-plane
        eda.nokia.com/app: eda-toolbox
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: eda.nokia.com/app-group
                      operator: In
                      values:
                        - control-plane
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: eda.nokia.com/app-group
                    operator: In
                    values:
                      - control-plane
      serviceAccountName: eda-toolbox
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: core # kpt-set: ${CORE_IMG_CREDENTIALS}
      containers:
        - name: eda-toolbox
          image: ghcr.io/nokia-eda/core/eda-toolbox:25.8.2 # kpt-set: ${EDA_TOOLBOX_IMG}
          # In Openshift environment we uncomment the below lines
          # securityContext:
          #   privileged: true
          env:
            - name: EDA_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TERM
              value: xterm-256color
          volumeMounts:
            - mountPath: /var/run/eda/tls/internal/client
              name: tls
            - mountPath: /var/run/eda/tls/internal/trust
              name: trustbundle
            - mountPath: /var/run/eda/tls/node
              name: node-trustbundle
            - mountPath: /var/run/eda/tls/api
              name: api-trustbundle
      volumes:
        - csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/dns-names: eda-toolbox,eda-toolbox.${POD_NAMESPACE}.svc,eda-toolbox.${POD_NAMESPACE}.svc.cluster,eda-toolbox.${POD_NAMESPACE}.svc.cluster.local,eda # kpt-set: eda-toolbox,eda-toolbox.${POD_NAMESPACE_IN_CSI}.svc,eda-toolbox.${POD_NAMESPACE_IN_CSI}.svc.cluster,eda-toolbox.${POD_NAMESPACE_IN_CSI}.svc.cluster.local,eda
              csi.cert-manager.io/issuer-name: eda-internal-issuer
          name: tls
        - configMap:
            defaultMode: 420
            name: eda-internal-trust-bundle
            optional: false
          name: trustbundle
        - configMap:
            defaultMode: 420
            name: eda-node-trust-bundle
            optional: false
          name: node-trustbundle
        - configMap:
            defaultMode: 420
            name: eda-api-trust-bundle
            optional: false
          name: api-trustbundle
