apiVersion: v1
kind: Secret
metadata:
  name: eda-api-client-secret
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/backup: "true"
type: Opaque
data:
  clientName: ZWRhLWFwaS1zZXJ2ZXI=

# To change clientName/clientKey -- echo -n "key" | base64
