apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvL25va2lhLWVkYSI6eyJ1c2VybmFtZSI6Im5va2lhLWVkYS1ib3QiLCJwYXNzd29yZCI6ImdocF95ZThaNzBuUUdwV1VnVU1VUDdIblluV3dQa3hYZzQ0UE5yeWciLCJlbWFpbCI6ImVkYUBub2tpYS5jb20iLCJhdXRoIjoiYm05cmFXRXRaV1JoTFdKdmREcG5hSEJmYlZKVlFWZGtSM0ZEVmsxQmFVTXhha2d6Y21ORVVuTTJhRmRyTUhSUU5FNUxaV053In19fQ==
kind: Secret
metadata:
  name: gitlab-core # kpt-set: ${CORE_IMG_CREDENTIALS}
type: kubernetes.io/dockerconfigjson
