apiVersion: v1
kind: Secret
metadata:
  labels:
    eda.nokia.com/backup: "true"
  name: git-secret
type: kubernetes.io/basic-auth
data:
  username: ZWRh
  password: ZWRh

# To change username/password -- echo -n "protoengine" | base64
