apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/backup: "true"
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4= # kpt-set: ${SECRET_KC_ADMIN_USERNAME}
  password: YWRtaW4= # kpt-set: ${SECRET_KC_ADMIN_PASSWORD}

# To change username/password -- echo -n "key" | base64
