apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/backup: "true"
type: kubernetes.io/basic-auth
data:
  username: cG9zdGdyZXM= # kpt-set: ${SECRET_PG_DB_USERNAME}
  password: cGFzc3dvcmQ= # kpt-set: ${SECRET_PG_DB_PASSWORD}

# To change username/password -- echo -n "key" | base64
