apiVersion: topologies.eda.nokia.com/v1alpha1
kind: TopologyGrouping
metadata:
  name: role
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  uiName: Role
  uiDescription: Assign nodes to tiers based on eda.nokia.com/role labels.
  tierSelectors:
  - tier: 1
    nodeSelector:
    - eda.nokia.com/role=backbone
  - tier: 2
    nodeSelector:
    - eda.nokia.com/role=superspine
  - tier: 3
    nodeSelector:
    - eda.nokia.com/role=spine
  - tier: 4
    nodeSelector:
    - eda.nokia.com/role=leaf
  - tier: 4
    nodeSelector:
    - eda.nokia.com/role=borderleaf
  - tier: 4
