apiVersion: core.eda.nokia.com/v1
kind: IndexAllocationPool
metadata:
  name: evi-pool
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  segments:
  - start: 100
    size: 4000
