apiVersion: core.eda.nokia.com/v1
kind: IPInSubnetAllocationPool
metadata:
  name: ip-in-subnet-pool
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  segments:
  - subnet: 10.1.0.0/16
