apiVersion: core.eda.nokia.com/v1
kind: IndexAllocationPool
metadata:
  name: lag-admin-key-pool
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  segments:
  - start: 1
    size: 65535
