apiVersion: core.eda.nokia.com/v1
kind: IndexAllocationPool
metadata:
  name: mirror-sdp-pool
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  segments:
  - start: 7000
    size: 1000
