apiVersion: core.eda.nokia.com/v1
kind: IPAllocationPool
metadata:
  name: systemipv6-pool
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  segments:
  - subnet: 121::0/64
