apiVersion: cx.eda.nokia.com/v1alpha1
kind: CxImage
metadata:
  name: srlinux-ghcr-24.7.2
spec:
  operatingSystem: srl
  image: ghcr.io/nokia/srlinux:24.7.2-319 # kpt-set: ${SRL_24_7_2_GHCR}
  imagePullSecret: gitlab-core # kpt-set: ${CORE_IMG_CREDENTIALS}
  version: 24.7.2
  command: ["bash", "-c", "/init/entrypoint-embedcfg.sh"]
