apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-node-trust-bundle
  labels:
    eda.nokia.com/backup: "true"
spec:
  sources:
  - secret:
      selector:
        matchLabels:
          eda.nokia.com/ca: "node"
      key: "ca.crt"
  - configMap:
      selector:
        matchLabels:
          eda.nokia.com/ca: "node"
      key: "ca.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-api-trust-bundle
  labels:
    eda.nokia.com/backup: "true"
spec:
  sources:
  - secret:
      selector:
        matchLabels:
          eda.nokia.com/ca: "api"
      key: "ca.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: eda-internal-trust-bundle
  labels:
    eda.nokia.com/backup: "true"
spec:
  sources:
  - secret:
      selector:
        matchLabels:
          eda.nokia.com/ca: "internal"
      key: "ca.crt"
  target:
    configMap:
      key: "trust-bundle.pem"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
