apiVersion: v1
kind: Service
metadata:
  name: eda-git
  namespace: eda-system # kpt-set: ${EDA_GOGS_NAMESPACE}
  labels:
    eda.nokia.com/app: git
spec:
  type: LoadBalancer # kpt-set: ${GIT_SVC_TYPE}
  ports:
  - port: 22
    name: ssh
  - port: 3000
    name: web
  selector:
    eda.nokia.com/app: git
