apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eda-git-pv-claim
  namespace: eda-system # kpt-set: ${EDA_GOGS_NAMESPACE}
  labels:
    eda.nokia.com/app: git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi # kpt-set: ${GOGS_PV_CLAIM_SIZE}
