apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eda-api-ingress-cert
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
spec:
  secretName: eda-api-ingress-secret
  issuerRef:
    name: eda-api-issuer
    kind: Issuer
  dnsNames:
    - "" # kpt-set: ${EXT_DOMAIN_NAME}
  ipAddresses:
    - "" # kpt-set: ${EXT_IPV4_ADDR}
    - "" # kpt-set: ${EXT_IPV6_ADDR}
  usages:
    - server auth
    - client auth
