apiVersion: core.eda.nokia.com/v1
kind: NodeProfile
metadata:
  name: srlinux-ghcr-25.10.3
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  nodeUser: admin
  operatingSystem: srl
  port: 57400
  version: 25.10.3
  versionPath: .system.information.version
  versionMatch: v25\.10\.3.*
  yang: https://eda-asvr.eda-system.svc/_base_/schemaprofiles/srlinux-ghcr-25.10.3/srlinux-25.10.3.zip # kpt-set: https://eda-asvr.${EDA_CORE_NAMESPACE}.svc/_base_/schemaprofiles/srlinux-ghcr-25.10.3/srlinux-25.10.3.zip
  llmDb: https://eda-asvr.eda-system.svc/_base_/llm-dbs/llm-db-srlinux-ghcr-25.10.3/llm-embeddings-srl-25-10-3.tar.gz # kpt-set: https://eda-asvr.${EDA_CORE_NAMESPACE}.svc/_base_/llm-dbs/llm-db-srlinux-ghcr-25.10.3/llm-embeddings-srl-25-10-3.tar.gz
  dhcp:
    managementPoolv4: 'ipv4-mgmt-pool'
    dhcp4Options:
    - option: 6-DomainNameServer
      value:
      - 128.251.10.125
  license: cx-srl-25-10-3-ghcr-license
  images:
  - image: _base_/srlimages/srlinux-25.10.3-449
    imageMd5: _base_/srlimages/srlinux-25.10.3-449-md5
  containerImage: ghcr.io/nokia/srlinux:25.10.3-449 # kpt-set: ${SRL_25_10_3_GHCR}
  imagePullSecret: core # kpt-set: ${CORE_IMG_CREDENTIALS}
