apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-asvr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-asvr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eda-asvr-admin
subjects:
- kind: ServiceAccount
  name: eda-asvr
  namespace: default
roleRef:
  kind: ClusterRole
  name: eda-asvr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: core.eda.nokia.com/v1
kind: HttpProxy
metadata:
  name: asvr
spec:
  authType: atDestination
  rootUrl: https://eda-asvr/
