apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-bsvr-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - artifacts.eda.nokia.com
  resources:
  - artifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.eda.nokia.com
  resources:
  - globalconfigs
  - nodesecurityprofiles
  - targetnodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.eda.nokia.com
  resources:
  - targetnodes/status
  verbs:
  - get
  - update
- apiGroups:
  - core.eda.nokia.com
  resources:
  - toponodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
