apiVersion: v1
kind: Service
metadata:
  name: eda-aggsvr-svc
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/app: configengine
spec:
  type: ClusterIP
  selector:
    eda.nokia.com/app: configengine
  ports:
  - port: 443
    targetPort: 10443
