apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-ce
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-ce-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eda-ce-admin
subjects:
- kind: ServiceAccount
  name: eda-ce
  namespace: default
roleRef:
  kind: ClusterRole
  name: eda-ce-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eda-ce
  labels:
    eda.nokia.com/app-group: control-plane
    eda.nokia.com/app: configengine
spec:
  selector:
    matchLabels:
      eda.nokia.com/app: configengine
  replicas: 1
  template:
    metadata:
      labels:
        eda.nokia.com/app-group: control-plane
        eda.nokia.com/app: configengine
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: eda.nokia.com/app-group
                      operator: In
                      values:
                        - control-plane
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: eda.nokia.com/app-group
                    operator: In
                    values:
                      - control-plane
      serviceAccountName: eda-ce
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: gitlab-core # kpt-set: ${CORE_IMG_CREDENTIALS}
      containers:
        - name: eda-ce
          image: ghcr.io/nokia-eda/core/config-engine:24.8.1-rc # kpt-set: ${CE_IMG}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HTTP_PROXY
              value: "http://usfraaa-proxy.americas.nsn-net.net:8080" # kpt-set: ${HTTP_PROXY}
            - name: HTTPS_PROXY
              value: "http://usfraaa-proxy.americas.nsn-net.net:8080" # kpt-set: ${HTTPS_PROXY}
            - name: NO_PROXY
              value: "localhost,127.0.0.1,135.227.67.200,alcatel-lucent.com,mv.usa.alcatel.com,ih.lucent.com,sh.bel.alcatel.be,ion.nokia.net,lab.sk.alcatel-lucent.com,gitlabsr.nuq.ion.nokia.net,registry.gitlabsr.nuq.ion.nokia.net,rgw.gitlabsr.nuq.ion.nokia.net,s3.nuq.ion.nokia.net,pulp.us.alcatel-lucent.com,sw.mv.usa.alcatel.com,artifactory.nuq.ion.nokia.net,artifactory-fpark1.int.net.nokia.com,artifactory-espoo1.int.net.nokia.com,artifactory-espoo2.int.net.nokia.com" # kpt-set: ${NO_PROXY}
            - name: http_proxy
              value: "http://usfraaa-proxy.americas.nsn-net.net:8080" # kpt-set: ${http_proxy}
            - name: https_proxy
              value: "http://usfraaa-proxy.americas.nsn-net.net:8080" # kpt-set: ${https_proxy}
            - name: no_proxy
              value: "localhost,127.0.0.1,135.227.67.200,alcatel-lucent.com,mv.usa.alcatel.com,ih.lucent.com,sh.bel.alcatel.be,ion.nokia.net,lab.sk.alcatel-lucent.com,gitlabsr.nuq.ion.nokia.net,registry.gitlabsr.nuq.ion.nokia.net,rgw.gitlabsr.nuq.ion.nokia.net,s3.nuq.ion.nokia.net,pulp.us.alcatel-lucent.com,sw.mv.usa.alcatel.com,artifactory.nuq.ion.nokia.net,artifactory-fpark1.int.net.nokia.com,artifactory-espoo1.int.net.nokia.com,artifactory-espoo2.int.net.nokia.com" # kpt-set: ${no_proxy}
          volumeMounts:
            - mountPath: /var/run/eda/tls/internal/client
              name: tls
            - mountPath: /var/run/eda/tls/internal/trust
              name: trustbundle
            - mountPath: /var/run/eda/tls/georedundant/client
              name: georedundant-tls
            - mountPath: /var/run/eda/tls/georedundant/trust
              name: georedundant-trustbundle
      volumes:
        - csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/dns-names: eda-ce,eda-ce.${POD_NAMESPACE}.svc,eda-ce.${POD_NAMESPACE}.svc.cluster,eda-ce.${POD_NAMESPACE}.svc.cluster.local,eda
              csi.cert-manager.io/issuer-name: eda-internal-issuer
          name: tls
        - configMap:
            defaultMode: 420
            name: eda-internal-trust-bundle
            optional: false
          name: trustbundle
        - csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/dns-names: eda-ce,eda-ce.${POD_NAMESPACE}.svc,eda-ce.${POD_NAMESPACE}.svc.cluster,eda-ce.${POD_NAMESPACE}.svc.cluster.local,eda
              csi.cert-manager.io/issuer-name: eda-api-issuer
          name: georedundant-tls
        - configMap:
            defaultMode: 420
            name: eda-georedundant-trust-bundle
            optional: true
          name: georedundant-trustbundle
---
apiVersion: v1
kind: Service
metadata:
  name: eda-ce
  labels:
    eda.nokia.com/app: configengine
spec:
  type: ClusterIP
  selector:
    eda.nokia.com/app: configengine
  ports:
    - protocol: TCP
      port: 51200
      targetPort: 51200
      name: ce-grpc-port
