apiVersion: v1
kind: Service
metadata:
  name: eda-cx
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/app: cx
spec:
  type: ClusterIP
  selector:
    eda.nokia.com/app: cx
  ports:
    - protocol: TCP
      port: 52200
      targetPort: 52200
      name: cx-grpc-port
