apiVersion: v1
kind: ServiceAccount
metadata:
  name: eda-cx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-cx
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eda-cx-admin
subjects:
- kind: ServiceAccount
  name: eda-cx
  namespace: default
roleRef:
  kind: ClusterRole
  name: eda-cx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cx-cxdp-image
data:
  imageName: ghcr.io/nokia-eda/core/cxdp:24.8.2 # kpt-set: ${CXDP_IMG}
---
apiVersion: v1
kind: Service
metadata:
  name: eda-cx
  labels:
    eda.nokia.com/app: cx
spec:
  type: ClusterIP
  selector:
    eda.nokia.com/app: cx
  ports:
    - protocol: TCP
      port: 52200
      targetPort: 52200
      name: cx-grpc-port
