apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eda-cert-checker-admin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates/status
  verbs:
  - get
- apiGroups:
  - certcheck.eda.nokia.com
  resources:
  - certificatechecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certcheck.eda.nokia.com
  resources:
  - certificatechecks/finalizers
  verbs:
  - update
- apiGroups:
  - certcheck.eda.nokia.com
  resources:
  - certificatechecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.eda.nokia.com
  resources:
  - targetnodes
  verbs:
  - get
  - list
  - watch
