apiVersion: core.eda.nokia.com/v1
kind: NodeSecurityProfile
metadata:
  name: insecure
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  nodeSelector:
    - "eda.nokia.com/security-profile=insecure"
