apiVersion: core.eda.nokia.com/v1
kind: NodeSecurityProfile
metadata:
  name: unmanaged-tls
  namespace: eda # kpt-set: ${EDA_USER_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  nodeSelector:
    - "eda.nokia.com/security-profile=unmanaged"
  tls:
    trustBundle: "eda-node-trust-bundle"
