apiVersion: core.eda.nokia.com/v1
kind: NodeSecurityProfile
metadata:
  name: unmanaged-tls-skip-verify
  namespace: eda-system # kpt-set: ${EDA_CORE_NAMESPACE}
  labels:
    eda.nokia.com/bootstrap: "true"
spec:
  nodeSelector:
    - "eda.nokia.com/security-profile=unmanagedSkipVerify"
  tls:
    skipVerify: true
